server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: CKOJ
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ck_oj?useSSL=true&serverTimezone=UTC
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 1
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.ming.ckoj.entity # 别名扫描包
logging:
  level:
    com.ming.ckoj: debug
